kind: Deployment
apiVersion: apps/v1
metadata:
   name: kullay
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: kullay
   template:
      metadata:
        labels:
          app: kullay
      spec:
       containers:
        - name: kullay
          image: kullay/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
