kind: Service                             
apiVersion: v1
metadata:
  name: kullay
  labels:
    app: kullay
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kullay                    
  type: LoadBalancer                   
